# Generated by Django 4.0.3 on 2022-03-04 07:45

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, help_text='Аватар', null=True, upload_to=clients.models.get_path_upload_avatar),
        ),
    ]
