# Generated by Django 4.0.3 on 2022-03-04 08:49

import clients.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Аватар', null=True, upload_to=clients.models.get_path_upload_avatar),
        ),
    ]
