# Generated by Django 4.0.3 on 2022-03-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Широта', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Долгота', null=True),
        ),
    ]
